version: "3.7"
services:

  troload:
    build: troload 
    restart: "no"
    secrets:
      - db-password
    networks:
      - pgpods-network 

secrets:
  db-password:
    file: ./.secrets-db-password

networks:
  pgpods-network:
    external: true
