version: "3.7"
services:

  troload:
    container_name: troload
    image: jasmit/troload
    build:
      context: .
      target: debug
      dockerfile: ./Dockerfile
    restart: "no"
    ports:
      - 5678:5678
    secrets:
      - db-password
    networks:
      - pgpods-network 

secrets:
  db-password:
    file: ./.secrets-db-password

networks:
  pgpods-network:
    external: true
