#  Starting image
FROM python:3.12-slim-bookworm

#  Environment variables
ENV APP_HOME=/opt/app/TROLoad

#  Update to stay secure
RUN apt-get -y update && apt-get -y upgrade

#  Change the working directory to the application home 
WORKDIR $APP_HOME 

#  Check results
CMD ["/bin/bash"]
