---

- name: Deploy the TROLoadTrans application
  hosts: vagrant1
  gather_facts: true

  vars:
    env: devl
    app_version: feature/1.0.0
    github_ssh_key: "{{ ansible_user_dir }}/.ssh/github_{{ ansible_hostname }}"

  tasks:
    - name: Ensure the group 'appgroup' exist
      become: true
      ansible.builtin.group:
        name: appgroup
        state: present
        gid: 10000

    - name: Ensure the user 'appuser' exist
      become: true
      ansible.builtin.user:
        name: appuser
        group: appgroup
        comment: User with minimal privilages used to run the application
        state: present
        shell: /bin/bash
        uid: 10000
        hidden: true

    - name: The application home for macOS
      ansible.builtin.set_fact:
        app_home: "/Users/appuser/{{ env }}/TROLoadTrans"
      when: ansible_distribution == 'Darwin'

    - name: The application home for Linux
      ansible.builtin.set_fact:
        app_home: "/home/appuser/{{ env }}/TROLoadTrans"
      when: ansible_distribution == 'Debian'

    - name: Display value
      ansible.builtin.debug:
        msg: "app_home={{ app_home }}"

    - name: Create the application's home
      become: true
      ansible.builtin.file:
        path: "{{ app_home }}"
        state: directory
        group: appgroup
        owner: appuser
        mode: '0750'
        recurse: true

    - name: Install Git
      become: true
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true

    - name: Generate ssh key pair
      community.crypto.openssh_keypair:
        path: "{{ github_ssh_key }}"

    - name: Register key with GitHub
      community.general.github_deploy_key:
        owner: "jasmit35"
        repository: "TROLoad"
        name: "github-deploy-key"
        key: "{{ github_ssh_key }}"
        force: true
        token: "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"

    - name: Copy the code from GitHub
      ansible.builtin.git:
        repo: git@github.com:jasmit35/TROLoad.git
        dest: /tmp/TROLoad
        single_branch: true
        version: "{{ app_version }}"

...
