---
- name: Deploy the TROLoadTrans application
  hosts: vagrant1
  gather_facts: true

  vars:
    env: devl
    app_name: TROLoadTrans
    app_version: feature/1.0.0
    github_ssh_key: "{{ ansible_user_dir }}/.ssh/github_{{ ansible_hostname }}"

  tasks:
    - name: Ensure the user 'appowner' exist
      become: true
      ansible.builtin.user:
        name: appowner
        group: appgroup
        comment: User that ownes the application
        state: present
        shell: /bin/bash
        uid: 10001
        hidden: true

    - name: Ensure the user 'appuser' exist
      become: true
      ansible.builtin.user:
        name: appuser
        group: appgroup
        comment: User with enough privilages to run the application
        state: present
        shell: /bin/bash
        uid: 10000
        hidden: true

    - name: The application home for macOS
      ansible.builtin.set_fact:
        app_home: "/Users/appowner/{{ env }}/{{ app_name }}"
      when: ansible_distribution == 'Darwin'

    - name: The application home for Linux
      ansible.builtin.set_fact:
        app_home: "/home/appowner/{{ env }}/{{ app_name }}"
      when: ansible_distribution == 'Debian'

    - name: Display value
      ansible.builtin.debug:
        msg: "app_home={{ app_home }}"

    - name: Create the application's home
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        group: appgroup
        owner: appowner
        mode: "0750"
      loop:
        - "{{ app_home }}"
        - "{{ app_home }}/logs"
        - "{{ app_home }}/reports"
        - "{{ app_home }}/stage"

    - name: Copy the code from GitHub
      ansible.builtin.git:
        repo: https://github.com/jasmit35/TROLoad.git
        dest: /tmp/TROLoad
        version: "{{ app_version }}"
