---
- name: Run the task needed on the remote server

  hosts: vagrant1

  vars:
    app_home: /home/appowner
    env: devl

  tasks:
    - name: Copy the Makefile
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/TROLoad/Makefile
        dest: "{{ app_home }}/{{ env }}/TROLoadTrans"
        owner: appowner
        group: appgroup
        mode: "0644"

    - name: Update the /etc/hosts file
      become: true
      ansible.builtin.template:
        src: etc_hosts_linux.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"

    - name: Ensure daily run of TROLoadTrans is scheduled
      become: true
      ansible.builtin.cron:
        user: "appuser"
        name: "Daily TROLoadTrans"
        minute: "0"
        hour: "9"
        weekday: "*"
        job: "make dr-run"
