
GRANT USAGE ON SCHEMA tro TO tro_rw;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA tro TO tro_rw;

GRANT UPDATE ON ALL SEQUENCES IN SCHEMA tro TO tro_rw;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON all tables IN SCHEMA tro TO tro_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA tro GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO tro_rw;

--

GRANT USAGE ON SCHEMA tro TO tro_ro;

GRANT SELECT ON  ALL TABLES IN SCHEMA tro TO tro_ro;

ALTER DEFAULT PRIVILEGES IN SCHEMA tro GRANT SELECT ON  TABLES TO tro_ro;

